#!/usr/bin/perl -w
             
$q = chr(39);
$n = chr(10);
$d = chr(44);
@codeBlock = (
             '------------------------------P E R L-------------------------------',
             '#!/usr/bin/perl -w',
             '             ',
             '$q = chr(39);',
             '$n = chr(10);',
             '$d = chr(44);',
             '@codeBlock = (',
             '              );',
             '',
             '    for($i=27;$i<31;$i++) {',
             '        print $codeBlock[$i];',
             '        print $n',
             '    }',
             '    for($i=0;$i<109;$i++) {',
             '        print $codeBlock[26];',
             '        print $q;',
             '        print $codeBlock[$i];',
             '        print $q;',
             '        print $d;',
             '        print $n;',
             '    }',
             '    for($i=31;$i<44;$i++) {',
             '        print $codeBlock[$i];',
             '        print $n',
             '    }',
             '--------------------------------R U B Y-------------------------------',
             '               ',
             'def main',
             '  q = 34.chr',
             '  d = 44.chr',
             '  codeBlock = [',
             '  ]',
             '  for i in 46..52',
             '    puts codeBlock[i]',
             '  end',
             '  for i in 0..108',
             '    puts codeBlock[45] + q + codeBlock[i] + q + d',
             '  end',
             '  for i in 53..67',
             '    puts codeBlock[i]',
             '  end',
             'end',
             '',
             'main()',
             '------------------------------J A V A--------------------------------',
             '            ',
             'public class quineRelay',
             '{',
             '    public static void main(String [] args)',
             '    {',
             '        char q = 34;',
             '        char d = 44;',
             '        String[] list = {',
             '        };',
             '        for(int i = 70; i < 79; i++)',
             '            {',
             '                System.out.println(list[i]);',
             '            }',
             '        for(int i = 0; i < 109; i++)',
             '            {',
             '                System.out.println(list[69] + q + list[i] + q + d);',
             '            }',
             '        for(int i = 79; i < 94; i++)',
             '            {',
             '                System.out.println(list[i]);',
             '            }',
             '    }',
             '}',
             '-------------------------------C ++---------------------------------',
             '    ',
             '#include <iostream>',
             '#include <string>',
             ' ',
             'using namespace std;',
             ' ',
             'int main(int argc, char*argv[])',
             '{',
             '  char q = 34;',
             '  char d = 44;  string codeBlock[] = {',
             '  };',
             '  for(int i = 96; i < 100; i++)',
             '    {',
             '      cout << codeBlock[i] << endl;',
             '    }',
             '  for(int i = 0; i < 109; i++)',
             '    {',
             '      cout << codeBlock[95] + q + codeBlock[i] + q + d << endl;',
             '    }',
             '  for(int i = 100; i < 109; i++)',
             '    {',
             '      cout << codeBlock[i] << endl;',
             '    }',
             '  return 0;',
             '}',
             '----------------------------P Y T H O N ----------------------------',
             '         ',
             'def main():',
             '    d = chr(44)',
             '    q = chr(39)',
             '    codeBlock = [',
             '        ]',
             '    for x in range(1,7):',
             '        print codeBlock[x]',
             '    for x in range(0,109):',
             '        print codeBlock[2] + q + codeBlock[x] + q + d',
             '    for x in range(7,25):',
             '        print codeBlock[x]',
             '',
             'main()',
              );

    for($i=27;$i<31;$i++) {
        print $codeBlock[$i];
        print $n
    }
    for($i=0;$i<109;$i++) {
        print $codeBlock[26];
        print $q;
        print $codeBlock[$i];
        print $q;
        print $d;
        print $n;
    }
    for($i=31;$i<44;$i++) {
        print $codeBlock[$i];
        print $n
    }
